# Ordinal and label encoder

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Datasets/customer.csv')

In [3]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        50 non-null     int64
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [5]:
df.shape

(50, 5)

In [6]:
df_encoded = pd.get_dummies(df, columns=['gender'], dtype='int32', drop_first=True)

In [7]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          50 non-null     int64
 1   review       50 non-null     object
 2   education    50 non-null     object
 3   purchased    50 non-null     object
 4   gender_Male  50 non-null     int32
dtypes: int32(1), int64(1), object(3)
memory usage: 1.9+ KB

In [8]:
df_encoded.head()

   age   review education purchased  gender_Male
0   30  Average    School        No            0
1   68     Poor        UG        No            0
2   70     Good        PG        No            0
3   72     Good        PG        No            0
4   16  Average        UG        No            0

In [9]:
df_encoded.nunique()

age            41
review          3
education       3
purchased       2
gender_Male     2
dtype: int64

In [10]:
df_encoded['education'].unique()
df_encoded['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [11]:

df_encoded['education'] = pd.Categorical(
    df_encoded['education'],
    categories=['School', 'UG', 'PG'],
    ordered=True
).codes   
df_encoded['review'] = pd.Categorical(
    df_encoded['review'],
    categories=['Average', 'Poor', 'Good'],
    ordered=True
).codes

In [12]:
df_encoded.head()

   age  review  education purchased  gender_Male
0   30       0          0        No            0
1   68       1          1        No            0
2   70       2          2        No            0
3   72       2          2        No            0
4   16       0          1        No            0

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [14]:
df = df.iloc[:,2:]
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [15]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,:2],df['purchased'],test_size=0.2)

In [16]:
X_train.head()

     review education
6      Good    School
0   Average    School
48     Good        UG
47     Good        PG
29  Average        UG

In [17]:
oe = OrdinalEncoder(categories=[['Average', 'Poor', 'Good'],['School', 'UG', 'PG']])

In [18]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Average', 'Poor', 'Good'], ['School', 'UG', 'PG']])

In [19]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [20]:
X_train

array([[2., 0.],
       [0., 0.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [1., 2.],
       [0., 0.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [1., 2.],
       [1., 2.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.]])

In [21]:
oe.categories_

[array(['Average', 'Poor', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [22]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [23]:
le.fit(y_train)

LabelEncoder()

In [24]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [25]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [26]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 0])

# One hot encoding

In [27]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [28]:
df = pd.read_csv('Datasets/cars.csv')

In [29]:
len(df['brand'].unique())

32

In [30]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [31]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [32]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [33]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [35]:
pd.get_dummies(df, columns=['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [36]:
pd.get_dummies(df, columns=['fuel', 'owner'],drop_first=True, dtype=int)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

In [37]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,:4], df.iloc[:,:-1], test_size=0.2, random_state=42)

In [38]:
X_train

         brand  km_driven    fuel                 owner
6518      Tata       2560  Petrol           First Owner
6144     Honda      80000  Petrol          Second Owner
6381   Hyundai     150000  Diesel  Fourth & Above Owner
438     Maruti     120000  Diesel          Second Owner
5939    Maruti      25000  Petrol           First Owner
...        ...        ...     ...                   ...
5226  Mahindra     120000  Diesel           First Owner
5390    Maruti      80000  Diesel          Second Owner
860    Hyundai      35000  Petrol           First Owner
7603    Maruti      27000  Diesel           First Owner
7270    Maruti      70000  Petrol          Second Owner

[6502 rows x 4 columns]

In [39]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=int)

In [40]:
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']])

In [41]:
X_test_new = ohe.fit_transform(X_test[['fuel', 'owner']])

In [42]:
X_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]], shape=(6502, 7))

In [43]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new))

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], shape=(6502, 9), dtype=object)

In [44]:
counts = df['brand'].value_counts()

In [45]:
df['brand'].nunique()
threshold = 100

In [46]:
repl = counts[counts<=threshold].index

In [47]:
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [48]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype=int)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,0,1,0,0,0
8127,0,0,0,0,0,0,0,0,0,1,0,0,0

# column transformer

In [49]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [50]:
df = pd.read_csv('Datasets/covid_toy.csv')

In [51]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [52]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [53]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [54]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'], test_size=0.2)

In [55]:
X_train

    age  gender  fever   cough       city
4    65  Female  101.0    Mild     Mumbai
24   13  Female  100.0  Strong    Kolkata
43   22  Female   99.0    Mild  Bangalore
0    60    Male  103.0    Mild    Kolkata
9    64  Female  101.0    Mild      Delhi
..  ...     ...    ...     ...        ...
61   81  Female   98.0  Strong     Mumbai
12   25  Female   99.0  Strong    Kolkata
92   82  Female  102.0  Strong    Kolkata
5    84  Female    NaN    Mild  Bangalore
87   47    Male  101.0  Strong  Bangalore

[80 rows x 5 columns]

In [56]:
from sklearn.compose import ColumnTransformer

In [57]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OneHotEncoder(drop='first', dtype=int , sparse_output=False), ['gender', 'city']),
    ('tnf3', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough'])
], remainder='passthrough')

In [58]:
transformer.fit_transform(X_train)

array([[101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  65.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  13.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [103.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  60.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  31.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  16.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  40.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  38.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  24.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  26.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  42.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  44.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [100.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  27.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   5.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  51.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  69.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   5.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  23.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  24.        ],
       [104.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   6.        ],
       [103.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  19.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  56.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  51.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  10.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  68.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  14.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  65.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  11.        ],
       [100.86111111,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  51.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  12.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  74.        ],
       [100.86111111,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  82.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  55.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  73.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   8.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  34.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  11.        ],
       [103.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  70.        ],
       [102.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [104.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  17.        ],
       [100.86111111,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  79.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  66.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [100.86111111,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  71.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  69.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  81.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  47.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  50.        ],
       [100.86111111,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  20.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  60.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  10.        ],
       [100.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  27.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  25.        ],
       [100.86111111,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  34.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  16.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  73.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  49.        ],
       [100.86111111,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  23.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  81.        ],
       [ 99.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  25.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  82.        ],
       [100.86111111,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  47.        ]])

In [59]:
transformer.transform(X_test).shape

(20, 7)

# Pipeline

In [93]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.compose import ColumnTransformer

In [94]:
df = pd.read_csv('Datasets/titanic.csv')

In [95]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [96]:
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)

In [97]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [111]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size=0.2, random_state=42)

In [112]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [113]:
# Column Transformer
trf1 = ColumnTransformer([
    ('impute_age', SimpleImputer(), [2]),
    ('impute_embarked', SimpleImputer(strategy='most_frequent'), [6])
], remainder='passthrough')

In [114]:
# one hot encoding
trf2 = ColumnTransformer([
    ('ohe_sex_embarked', OneHotEncoder(sparse_output=False, handle_unknown='ignore'),[1,6])
], remainder='passthrough')

In [115]:
# Scaling
trf3 = ColumnTransformer([
    ('scale', MinMaxScaler(), slice(0,10))
])

In [116]:
# Feature selection
trf4 = SelectKBest(score_func=chi2, k=8)

In [117]:
trf5 = DecisionTreeClassifier()

In [118]:
# Pipeline
pipe = Pipeline([
    ('trf1', trf1),
    ('trf2', trf2),
    ('trf3', trf3),
    ('trf4', trf4),
    ('trf5', trf5)
])

In [119]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('trf3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('trf4',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x000001DAB0C4EF20>)),
                ('trf5', DecisionTreeClassifier())])

In [120]:
pipe.named_steps['trf1'].transformers_[0][1].statistics_

array([29.49884615])

In [121]:
pipe.named_steps['trf1'].transformers_[1][1].statistics_

array(['S'], dtype=object)

In [122]:
y_pred = pipe.predict(X_test)

In [123]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6256983240223464

# Cross validation

In [124]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

np.float64(0.6391214419383433)

# GridSearch Using Pipeline

In [125]:
params = {
    'trf5__max_depth':[1,2,3,4,5,None]
}

In [126]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trf1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('trf2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_sex_embarked',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         [1,
                                                                          6])])),
                                       ('trf3',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('trf4',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x000001DAB0C4EF20>)),
                                       ('trf5', DecisionTreeClassifier())]),
             param_grid={'trf5__max_depth': [1, 2, 3, 4, 5, None]},
             scoring='accuracy')

In [128]:
grid.best_score_

np.float64(0.6391214419383433)

In [129]:
grid.best_params_

{'trf5__max_depth': 2}

In [130]:
import pickle
pickle.dump(pipe, open('pipe.pkl', 'wb'))

In [133]:
import pickle
import numpy as np

In [134]:
pipe = pickle.load(open('pipe.pkl', 'rb'))

In [135]:
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [136]:
pipe.predict(test_input)

c:\Users\Parth chauhan\Desktop\Program\Machine Learning\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
c:\Users\Parth chauhan\Desktop\Program\Machine Learning\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(

array([0])